const newsAll = [
    {
        id:1,
        imageNews: "/images/news/secondBlock/profitably2_1.jpg",
        sortBlogText: "корисно",
        like:23,
        title: "4 інгредієнти для молодості шкіри обличчя.",
        text: "Вони здивують вас своєю ефективністю! Шкіра є найбільшим органом тіла і постійно є у контакті із шкідливими речовинами.",
        imageAuthor: "/images/news/author/author2.jpg",
        surnameAuthor: "Віталій Ступка",
        dateNews: "Квітень 21, 2019 18:35",
        topNewsSecond: true,
    },
    {
        id:2,
        imageNews: "/images/news/secondBlock/inspiration2_1.jpg",
        sortBlogText: "натхення",
        like:15,
        title: "Хобі, які неймовірно покращать ваше життя!",
        text: "Список з 5 хобі, завдяки яким ви зможете стати більш здоровою, щасливою і продуктивною людиною. Перевірте самі!",
        imageAuthor: "/images/news/author/author3.jpg",
        surnameAuthor: "Олексій Зінчук",
        dateNews: "Квітень 27, 2019 12:03",
        topNewsSecond: true,
    },
    {
        id:3,
        imageNews: "/images/news/secondBlock/interesting2_1.jpg",
        sortBlogText: "цікаво",
        like:31,
        title: "Цікаві факти про Тихий океан.",
        text: "Тихий океан - найбільша частина Світового океану, його площа більша всієї суші на планеті на стільки, що могла б «вмістити» ще одну Африку.",
        imageAuthor: "/images/news/author/author1.png",
        surnameAuthor: "Орест Левицький",
        dateNews: "Квітень 29, 2019 15:15",
        topNewsSecond: true,
    },
    {
        id:4,
        imageNews: "/images/news/thirdBlock/science3.jpg",
        sortBlogText: "наука",
        like:17,
        title: "Фізики з'ясували чому виноград спалахує у мікрохвильовці.",
        text: "У мікрохвильовці невеликі плоди винограду, за лічені секунди нагрівання ефектно займаються спалахами.",
        imageAuthor: "/images/news/author/author3.jpg",
        surnameAuthor: "Олексій Зінчук",
        dateNews: "Травень 1, 2019 23:03",
        topNewsThird: true,
    },
    {
        id:5,
        imageNews: "/images/news/thirdBlock/interesting3_2.jpg",
        sortBlogText: "цікаво",
        like:25,
        title: "Коли твій дім – ліс. Як люди проміняли квартири на життя поміж гір та дерев.",
        text: "Галявина біля водоспаду Шипіт, що на Закарпатті – це Мекка українських неформалів, які приїжджають сюди вже 23 роки.",
        imageAuthor: "/images/news/author/author1.png",
        surnameAuthor: "Орест Левицький",
        dateNews: "Травень 2, 2019 14:37",
        topNewsThird: true,
    },
    {
        id:6,
        imageNews: "/images/news/thirdBlock/inspiration3_2.jpg",
        sortBlogText: "натхення",
        like:14,
        title: "Найкращі книги для натхнення, віри і оптимізму: 5 must-read.",
        text: "Є книги, які буквально перевертають світогляд, нади-хають, наповнюють оптимізмом і вірою в себе.",
        imageAuthor: "/images/news/author/author2.jpg",
        surnameAuthor: "Віталій Ступка",
        dateNews: "Квітень 31, 2019 21:21",
        topNewsThird: true,
    },
    {
        id:7,
        imageNews: "/images/news/fourthBlock/science4_2.jpg",
        sortBlogText: "наука",
        like:24,
        title: "Які це купчасті хмари?",
        text: "Купчасті хмари — конвекційні хмари у вигляді куполів, бугрів, башт, що розвиваються в вертикальному напрямку. Вони мають вид ізольованих хмарних мас, вертикальні розміри яких порівнянні з горизонтальними.",
        imageAuthor: "/images/news/author/author3.jpg",
        surnameAuthor: "Олексій Зінчук",
        dateNews: "Травень 3, 2019 08:43",
        topNewsFourth: true,
    },
    {
        id:8,
        imageNews: "/images/news/fourthBlock/interesting4_3.jpg",
        sortBlogText: "цікаво",
        like:25,
        title: "Виникнення і розвиток письма.",
        text: "Мова і письмо з'явилися не вод­ночас. Звукова мова виникла, можливо, 2 млн. років тому. Письму ж не більше 6—7 тис. років. Письмо має велике значення в розвитку людини й суспільства. Письмо — це система умовних лінійних (графічних) знаків.",
        imageAuthor: "/images/news/author/author1.png",
        surnameAuthor: "Орест Левицький",
        dateNews: "Травень 3, 2019 15:07",
        topNewsFourth: true,
    },
 ]

 export default newsAll